### ISSUE TITLE
Переименовать SelfResolver во что-то более понятное

### ISSUE THREAD

**Issue by artem-prozorov** [zebrainsteam/repos#13]
`SelfResolver` плохо отображает суть происходящего, предлагаю переименовать этот класс во что-то типа `HasRepositoryResolver`
@manzor29 что скажешь?

**Comment by manzor29** [comment]
Да, согласен, что название не совсем удачное. Для выбора окончательного варианта предлагаю к твоему еще пару: `ExistingRepositoryResolver` `AvailableRepositoryResolver`

**Comment by artem-prozorov** [comment]
Will be fixed in v2
